---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        # args:
        #   - "--disable-rule=terraform_module_pinned_source"

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        types_or: [python, pyi]
        args: # arguments to configure black
          - --line-length=120

  # - repo: https://github.com/terraform-docs/terraform-docs
  #   rev: v0.16.0
  #   hooks:
  #     - id: terraform-docs-system
  #       args: ['./examples/complete']
  #     - id: terraform-docs-system
  #       args: ['.']
