bgp:
  asn: 65002
  enhanced_error: false
  template_peers:
  - address_families:
    - address_family: l2vpn_evpn
      route_reflector_client: true
      send_community_extended: true
      send_community_standard: true
    asn: 65002
    name: LEAF-PEERS
    source_interface: lo0
  vrfs:
  - graseful_restart_restart_time: 300
    graseful_restart_stalepath_time: 1800
    log_neighbor_changes: true
    neighbors:
    - description: leaf switches
      inherit_peer: LEAF-PEERS
      ip: 172.16.0.0/24
    router_id: 172.16.1.2
    vrf: default
features:
- ospf
- bgp
- nv_overlay
- evpn
- vn_segment
- ssh
- interface_vlan
hostname: site-1-spine-2
interfaces_ethernet:
- description: underlay interface
  id: 1/1
  ipv4_address: 169.254.2.1/31
  layer3: true
  link_debounce_down: 0
  mtu: 9216
- description: underlay interface
  id: 1/2
  ipv4_address: 169.254.2.3/31
  layer3: true
  link_debounce_down: 0
  mtu: 9216
interfaces_loopback:
- description: Router ID
  id: '0'
  ipv4_address: 172.16.1.2/32
ospf:
- name: underlay
  vrfs:
  - adjancency_logging_level: detail
    bandwidth_reference: 1000
    banwidth_reference_unit: gbps
    interfaces:
    - area: 0.0.0.0
      interface: lo0
    - area: 0.0.0.0
      interface: eth1/1
      network_type: p2p
    - area: 0.0.0.0
      interface: eth1/2
      network_type: p2p
    router_id: 172.16.1.2
    vrf: default
vrfs:
- name: default
