bgp:
  asn: 65002
  enhanced_error: false
  template_peers:
  - address_families:
    - address_family: l2vpn_evpn
      send_community_extended: true
      send_community_standard: true
    asn: 65002
    name: SPINE-PEERS
    source_interface: lo0
  vrfs:
  - graseful_restart_restart_time: 300
    graseful_restart_stalepath_time: 1800
    log_neighbor_changes: true
    neighbors:
    - description: site-1-spine-1
      inherit_peer: SPINE-PEERS
      ip: 172.16.1.1
    - description: site-1-spine-2
      inherit_peer: SPINE-PEERS
      ip: 172.16.1.2
    router_id: 172.16.0.2
    vrf: default
fabric_forwarding:
  anycast_gateway_mac: '20:20:00:00:10:12'
  anycast_gateway_vlans: []
features:
- ospf
- bgp
- nv_overlay
- evpn
- vn_segment
- ssh
- interface_vlan
hostname: site-1-leaf-2
interface_nve:
  admin_state: true
  hold_down_time: 300
  host_reachability_protocol: bgp
  ingress_replication_protocol_bgp: true
  source_interface: lo0
  vnis: []
interfaces_ethernet:
- description: underlay interface
  id: 1/6
  ipv4_address: 169.254.1.2/31
  layer3: true
  link_debounce_down: 0
  mtu: 9216
- description: underlay interface
  id: 1/7
  ipv4_address: 169.254.2.2/31
  layer3: true
  link_debounce_down: 0
  mtu: 9216
interfaces_loopback:
- description: Router ID
  id: '0'
  ipv4_address: 172.16.0.2/32
interfaces_vlan: []
ospf:
- name: underlay
  vrfs:
  - adjancency_logging_level: detail
    bandwidth_reference: 1000
    banwidth_reference_unit: gbps
    interfaces:
    - area: 0.0.0.0
      interface: lo0
    - area: 0.0.0.0
      interface: eth1/6
      network_type: p2p
    - area: 0.0.0.0
      interface: eth1/7
      network_type: p2p
    router_id: 172.16.0.2
    vrf: default
vlans: []
vrfs:
- name: default
