bgp:
  asn: 65002
  enhanced_error: false
  template_peers:
  - address_families:
    - address_family: l2vpn_evpn
      send_community_extended: true
      send_community_standard: true
    asn: 65002
    name: SPINE-PEERS
    source_interface: lo0
  vrfs:
  - graseful_restart_restart_time: 300
    graseful_restart_stalepath_time: 1800
    log_neighbor_changes: true
    neighbors:
    - description: site-1-spine-1
      inherit_peer: SPINE-PEERS
      ip: 172.16.1.1
    - description: site-1-spine-2
      inherit_peer: SPINE-PEERS
      ip: 172.16.1.2
    router_id: 172.16.0.1
    vrf: default
features:
- ospf
- bgp
- nv_overlay
- evpn
- vn_segment
- ssh
- interface_vlan
hostname: site-1-leaf-1
interface_nve:
  admin_state: true
  hold_down_time: 300
  host_reachability_protocol: bgp
  ingress_replication_protocol_bgp: true
  source_interface: lo0
interfaces_ethernet:
- description: underlay interface
  id: 1/6
  ipv4_address: 169.254.1.0/31
  layer3: true
  link_debounce_down: 0
  mtu: 9216
- description: underlay interface
  id: 1/7
  ipv4_address: 169.254.2.0/31
  layer3: true
  link_debounce_down: 0
  mtu: 9216
interfaces_loopback:
- description: Router ID
  id: '0'
  ipv4_address: 172.16.0.1/32
interfaces_vlan:
- description: Some tenant
  id: 3901
  ip_forward: true
  mtu: 9216
  vrf: TENANT-1
- description: Some tenant
  id: 3902
  ip_forward: true
  mtu: 9216
  vrf: TENANT-2
- description: service-tenant-1-a
  id: 101
  mtu: 9216
  vrf: TENANT-1
- description: service-tenant-1-b
  id: 102
  mtu: 9216
  vrf: TENANT-1
- description: service-tenant-2-a
  id: 103
  mtu: 9216
  vrf: TENANT-2
- description: service-tenant-2-b
  id: 104
  mtu: 9216
  vrf: TENANT-2
ospf:
- name: underlay
  vrfs:
  - adjancency_logging_level: detail
    bandwidth_reference: 1000
    banwidth_reference_unit: gbps
    interfaces:
    - area: 0.0.0.0
      interface: lo0
    - area: 0.0.0.0
      interface: eth1/6
      network_type: p2p
    - area: 0.0.0.0
      interface: eth1/7
      network_type: p2p
    router_id: 172.16.0.1
    vrf: default
vlans:
- id: 101
  name: service-tenant-1-a
- id: 102
  name: service-tenant-1-b
- id: 103
  name: service-tenant-2-a
- id: 104
  name: service-tenant-2-b
vrfs:
- name: default
- address_families:
  - address_family: ipv4_unicast
    route_target_both_auto: true
    route_target_both_auto_evpn: true
  description: Some tenant
  name: TENANT-1
  route_distinguisher: auto
  vni: 103901
- address_families:
  - address_family: ipv4_unicast
    route_target_both_auto: true
    route_target_both_auto_evpn: true
  description: Some tenant
  name: TENANT-2
  route_distinguisher: auto
  vni: 103902
